// Code generated by scorify, DO NOT EDIT.
// Import generated from "github.com/ams4222/adcs@v0.0.1"

package checks

import (
	"github.com/scorify/schema"

	adcs "github.com/ams4222/adcs"
)

func init() {
	schema, err := schema.Describe(adcs.Schema{})
	if err != nil {
		panic(err)
	}

	Checks["adcs"] = Check{
		Func:     adcs.Run,
		Validate: adcs.Validate,
		Schema:   schema,
	}
}