// Code generated by scorify, DO NOT EDIT.
// Import generated from "github.com/ams4222/http@v0.0.1"

package checks

import (
	"github.com/scorify/schema"

	httpauth "github.com/ams4222/http"
)

func init() {
	schema, err := schema.Describe(httpauth.Schema{})
	if err != nil {
		panic(err)
	}

	Checks["httpauth"] = Check{
		Func:     httpauth.Run,
		Validate: httpauth.Validate,
		Schema:   schema,
	}
}