// Code generated by scorify, DO NOT EDIT.
// Import generated from "github.com/bdawg295/http@v0.0.0"

package checks

import (
	"github.com/scorify/schema"

	http "github.com/bdawg295/http"
)

func init() {
	schema, err := schema.Describe(http.Schema{})
	if err != nil {
		panic(err)
	}

	Checks["http"] = Check{
		Func:     http.Run,
		Validate: http.Validate,
		Schema:   schema,
	}
}