// Code generated by scorify, DO NOT EDIT.
// Import generated from "github.com/jjtech0130/scorify-mongodb@v0.0.4"

package checks

import (
	"github.com/scorify/schema"

	mongodb "github.com/jjtech0130/scorify-mongodb"
)

func init() {
	schema, err := schema.Describe(mongodb.Schema{})
	if err != nil {
		panic(err)
	}

	Checks["mongodb"] = Check{
		Func:     mongodb.Run,
		Validate: mongodb.Validate,
		Schema:   schema,
	}
}