// Code generated by scorify, DO NOT EDIT.
// Import generated from "github.com/pmj1426/mssql2@v0.0.2"

package checks

import (
	"github.com/scorify/schema"

	mssql "github.com/pmj1426/mssql2"
)

func init() {
	schema, err := schema.Describe(mssql.Schema{})
	if err != nil {
		panic(err)
	}

	Checks["mssql"] = Check{
		Func:     mssql.Run,
		Validate: mssql.Validate,
		Schema:   schema,
	}
}