// Code generated by scorify, DO NOT EDIT.
// Import generated from "github.com/bdawg295/telnet@v0.0.0"

package checks

import (
	"github.com/scorify/schema"

	telnet "github.com/bdawg295/telnet"
)

func init() {
	schema, err := schema.Describe(telnet.Schema{})
	if err != nil {
		panic(err)
	}

	Checks["telnet"] = Check{
		Func:     telnet.Run,
		Validate: telnet.Validate,
		Schema:   schema,
	}
}